version: 0.0
os: linux
files:
  - source: /frontend.zip
    destination: /opt/taskapp/frontend
  - source: /backend.zip
    destination: /opt/taskapp/backend
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
